#!/usr/bin/env python3
"""
mandelbrot_logical.py -- the Mandelbrot set generated by closure, one way.

THE QUESTION (Jim, 2026-09-26): "find the mandelbrot set generation quantum logically
(active inference) in any one way", after "look first at simple chaos emergence"
(`chaos_emergence.py`).

THE MOVE, in one construction -- not the route, a route (CLAUDE.md sec 3a rule 5).

  * THE LOGICAL RULE. `mandelbrot_loop_dna.py` translates the quadratic loop to one
    conjugate pair: squaring `z |-> z^2` is the itinerary COPIED (`W |-> W W`) and `+c`
    is ONE SPLICE TWIST. The critical orbit is then literally a twist history, read as a
    sequence of closures.

  * ACTIVE INFERENCE. An agent integrates only closures it can complete inside its
    Markov blanket's capacity R: a state whose free action leaves the horizon is not a
    closure it can hold, so the orbit has left (`QLF_ClosureDepthLaw`:
    `closedAtHorizon_iff_maxExcursion_le`). Every closure event is the 50/50 partition
    carrying D_KL = log 2 (`active_inference_vfe_demo.py`). At capacity R the agent's
    closure set is therefore

        M_R  =  { c : the critical orbit of z |-> z^2 + c has not escaped in R steps }.

    M_R shrinks with R and M = intersection over R. The finite-capacity set is the QLF
    object -- "the limit is a rendering, the finite-depth truncation is the object"
    (`Continuum_Choice_Fallacy.md`, `TheContinuum.md`).

  * THE SKELETON. The parameters where the critical loop closes EXACTLY in p steps are
    the superstable parameters -- the closure events of the set -- and they are found by
    solving `f_c^p(0) = 0`, a finite computation. Their periods are the set's skeleton:
    the period-doubling cascade `2^k` (generated by the loop DNA's `W |-> W.s.W`) plus
    the windows.

METHOD (sec 0). Rather than enumerate all ways, take the simplest path -- the least-free-
action closure, which is the one reachable the most ways (`QucalcSearch.md`, the `/solve`
selection). This script checks that first, because it is the selection the generation uses.

  sec 0  the simplest path is the one reachable the most ways (why /solve is the rule)
  sec 1  the logical rule, and the capacity-R generation M_R
  sec 2  the closure skeleton: superstable centres, the cascade, and the windows
  sec 3  the render -- one way
  sec 4  scope

Run:  python3 mandelbrot_logical.py
"""
from __future__ import annotations

import random

from qucalc_search import max_excursion, search, solve
from twist_core import generate_histories


def rule(t: str) -> None:
    print("\n" + "=" * 78 + "\n" + t + "\n" + "-" * 78)


# --------------------------------------------------------------------------- #
# sec 0 -- the method: the simplest path is the one reachable the most ways
# --------------------------------------------------------------------------- #
def horizon_reach() -> None:
    """Least free action = the closure the most listeners can hold."""
    rule("sec 0a  LEAST FREE ACTION = THE MOST LISTENERS")
    print("""
`QucalcSearch.md`: of the ways a position can close, the substrate takes ONE -- the least
free action, the shallowest-horizon closure, "the one reachable the most ways"
(`QLF_ClosureDepthLaw`). The part we can check directly is what "reachable" means for a
capacity-R listener: a closure of max excursion e is heard iff R >= e
(`closedAtHorizon_iff_maxExcursion_le`), so the least-excursion closure is the one EVERY
listener can hold -- strictly more listeners than any deeper closure. A listener's reach
also grows with R:
""")
    print(f"  {'capacity R':>12}{'histories within horizon':>26}")
    print("  " + "-" * 40)
    for R in (2, 4, 6):
        n = len(generate_histories("^", causal_horizon=R, require_zfa=False))
        print(f"  {R:>12}{n:>26}")
    print("""
  (R = 8 is ~7,000,000 and is skipped -- that blow-up is exactly why the repo takes
  `/solve`'s least-excursion pick instead of sweeping the horizon.) A shallow closure is
  inside every ball here; a deep one is inside none of the small ones. Least free action
  = the most listeners, and that is the selection the generation below uses.""")


def solve_is_simplest() -> None:
    """Compose the simple mechanisms and show /solve takes the least-excursion closure."""
    rule("sec 0b  /solve TAKES THE SIMPLEST PATH")
    print("""
The two simplest mechanisms are the minimal doubler (`^ -> ^<v> | ^>v<`, the electron /
positron pair) and the splice (one more twist). Compose them into a position and ask the
substrate which closure it takes:
""")
    for position in ("^", "^^<", "^<v>+-"):
        picked = solve(position, max_depth=6)
        if not picked.get("solved"):
            continue
        if picked.get("already_closed"):
            print(f"  position {position!r:<10} already a closure  ->  "
                  f"/solve takes {picked['history']!r} (excursion "
                  f"{picked['peak_excursion']})")
            continue
        events = list(search(position, max_depth=6, absorbing=True))
        if not events:
            continue
        min_exc = min(max_excursion(r["history"]) for r in events)
        agree = picked["peak_excursion"] == min_exc
        print(f"  position {position!r:<10} closures {len(events):>3}   "
              f"least excursion {min_exc}   "
              f"/solve takes {picked['history']!r} (excursion {picked['peak_excursion']})   "
              f"agrees: {agree}")
        assert agree, (position, picked, min_exc)
    print("""
  `/solve` is the deterministic cascade least peak excursion -> shortest depth -> phase +1
  -> lexicographic. Least peak excursion is least free action -- the shallowest-horizon
  closure, the one the most listeners can hold. The generation below uses exactly this.""")


# --------------------------------------------------------------------------- #
# sec 1 -- the logical rule and the capacity-R generation
# --------------------------------------------------------------------------- #
def escape_depth(c: complex, max_steps: int = 64, radius: float = 2.0) -> int:
    """Steps until |z| > radius, or max_steps if it never leaves (the capacity horizon)."""
    z = 0j
    for n in range(1, max_steps + 1):
        z = z * z + c
        if abs(z) > radius:
            return n
    return max_steps


def capacity_generation() -> None:
    rule("sec 1  THE CAPACITY-R GENERATION M_R")
    print("""
The logical rule (`mandelbrot_loop_dna.py`):
    z |-> z^2      the itinerary is COPIED           (the angle doubles -- squaring)
    + c            ONE SPLICE TWIST                  (the parameter is one letter)
An agent of capacity R holds the closures of the critical orbit up to R steps; a state
outside |z| <= 2 cannot be held, so the orbit has left its blanket. Generate:

    M_R = { c : the critical orbit has not escaped in R steps }.

M_R shrinks with R. Measure it on a sample:
""")
    rng = random.Random(20260926)
    print(f"  {'capacity R':>12}{'fraction of sample inside M_R':>32}")
    print("  " + "-" * 44)
    prev = None
    for R in (4, 8, 16, 32, 64):
        inside = total = 0
        for _ in range(40000):
            c = complex(rng.uniform(-2.1, 0.6), rng.uniform(-1.3, 1.3))
            total += 1
            if escape_depth(c, R) >= R:
                inside += 1
        frac = inside / total
        print(f"  {R:>12}{frac:>32.4f}")
        if prev is not None:
            assert frac <= prev + 0.02          # monotone up to sampling noise
        prev = frac
    print("""
  The fraction inside falls toward the true area of M as R grows: the truncation is the
  object, the limit its rendering. Every `c` in the intersection is a parameter at which
  the agent can complete every closure the orbit presents, forever.""")


# --------------------------------------------------------------------------- #
# sec 2 -- the closure skeleton
# --------------------------------------------------------------------------- #
def orbit(c: float, p: int) -> float:
    x = 0.0
    for _ in range(p):
        x = x * x + c
    return x


def real_centers(period_max: int = 8, steps: int = 6000) -> dict[int, list[float]]:
    """Real superstable parameters of minimal period <= period_max (f_c^p(0) = 0)."""
    grid = [-2.0 + 2.25 * i / steps for i in range(steps + 1)]
    roots: dict[int, list[float]] = {}
    for p in range(1, period_max + 1):
        found: list[float] = []
        for a, b in zip(grid, grid[1:]):
            fa, fb = orbit(a, p), orbit(b, p)
            if fa == 0.0:
                found.append(a)
            if fa * fb < 0.0:
                lo, hi = a, b
                for _ in range(60):
                    mid = 0.5 * (lo + hi)
                    if orbit(lo, p) * orbit(mid, p) <= 0.0:
                        hi = mid
                    else:
                        lo = mid
                found.append(0.5 * (lo + hi))
        minimal = [c for c in found
                   if all(abs(orbit(c, q)) > 1e-6 for q in range(1, p) if p % q == 0)]
        roots[p] = minimal
    return roots


def skeleton() -> None:
    rule("sec 2  THE CLOSURE SKELETON -- WHERE THE CRITICAL LOOP CLOSES EXACTLY")
    print("""
A parameter `c` is a CLOSURE EVENT when the critical loop closes exactly in p steps:
`f_c^p(0) = 0`. These are the superstable parameters -- the centres of the hyperbolic
components -- and finding them is a finite computation. Their periods are the set's
skeleton.
""")
    centers = real_centers(period_max=8)
    print(f"  {'period':>8}{'# real centres':>16}   {'centres (real axis)':<40}")
    print("  " + "-" * 68)
    for p in sorted(centers):
        cs = sorted(centers[p])
        shown = ", ".join(f"{c:+.4f}" for c in cs[:4])
        if len(cs) > 4:
            shown += ", ..."
        print(f"  {p:>8}{len(cs):>16}   {shown}")
    print("""
  The period-2^k column is the period-doubling cascade -- the skeleton the loop DNA
  `W |-> W.s.W` generates (`mandelbrot_loop_dna.py` sec 2, verified against exact Newton
  superstable parameters; `chaos_emergence.py`). The other periods are the windows
  (period 3 at c ~ -1.7549, ...), the tuned copies the renormalisation picture fills in.
  Every one is a finite closure: any way at all happens in finite time.

  So the generation is: closure events (this section) -> their bulbs -> M is the closure
  of the union. One way to generate the set, not the only way.
""")
    # the cascade is the DNA's: its exact Newton centres (mandelbrot_loop_dna.py) must
    # appear in the period columns above
    cascade = {1: 0.0, 2: -1.0, 4: -1.3107, 8: -1.38154}
    print("  the period-doubling cascade, generated by W |-> W.s.W:")
    for p, c in sorted(cascade.items()):
        near = min(centers[p], key=lambda x: abs(x - c))
        ok = abs(near - c) < 5e-3
        print(f"    period {p:>2}   centre {c:+.5f}   found {near:+.5f}   agrees: {ok}")
        assert ok


# --------------------------------------------------------------------------- #
# sec 3 -- the render
# --------------------------------------------------------------------------- #
def render(width: int = 78, height: int = 30, R: int = 64) -> None:
    rule("sec 3  THE RENDER (one way)")
    print(f"""
M_R drawn at capacity R = {R} -- one plane of closure events:
""")
    x0, x1 = -2.1, 0.6
    y0, y1 = -1.15, 1.15
    shades = " .:-=+*#%@"
    for row in range(height):
        im = y1 - (y1 - y0) * row / (height - 1)
        line = []
        for col in range(width):
            re = x0 + (x1 - x0) * col / (width - 1)
            n = escape_depth(complex(re, im), R)
            if n >= R:
                line.append("#")
            elif n < 4:
                line.append(shades[min(len(shades) - 1, n)])
            else:
                line.append(" ")
        print("  " + "".join(line))
    print("""
  `#` is inside the capacity-R set; the ramp is escape time (the free action spent
  leaving). The picture is a rendering of the finite closure object, not the object:
  the object is the closure census of sec 1-2.""")


# --------------------------------------------------------------------------- #
# sec 4 -- scope
# --------------------------------------------------------------------------- #
def scope() -> None:
    rule("sec 4  SCOPE")
    print("""
  1. ONE WAY. This is a construction, not the route (CLAUDE.md sec 3a rule 5). It renders
     the parameter plane by the direct escape condition and generates the skeleton by the
     closure condition `f_c^p(0) = 0`. Neither is claimed canonical.

  2. FINITE DEPTH. M_R is the object; M is its limit -- the same reading as
     `Continuum_Choice_Fallacy.md` / `TheContinuum.md`, and the same capacity-R listener
     as `QLF_ClosureDepthLaw`.

  3. THE SECOND AXIS IS OPEN. Only one conjugate pair is used (the real spine in the
     complex plane). The full 2D M as a purely combinatorial object needs the second axis,
     where Pauli order-sensitivity is non-trivial (`mandelbrot_loop_dna.py` sec 4, sec 6).
     That remains the open edge; this script does not claim it.

  4. NO DISCARDED CONSTANT. No Feigenbaum delta is computed or needed: the DNA is
     combinatorial and delta is class-dependent (rejected as a substrate constant,
     `Open_Problems.md`).""")


def main() -> None:
    print(__doc__)
    horizon_reach()
    solve_is_simplest()
    capacity_generation()
    skeleton()
    render()
    scope()


if __name__ == "__main__":
    main()
