#!/usr/bin/env python3
"""
z3_colour_derivation.py -- where the colour Z3 lives in QLF (Carbon_Superconductivity.md sec 24).

  N1  no twist fold has an eigenvalue of order 3: every fold's eigenvalues lie in mu_4 = {+-1, +-i}, so omega cannot be
      a fold phase or holonomy.
  N2  transport by folds never relabels the axes: conjugating sigma_x, sigma_y, sigma_z by any fold returns each to
      +- itself. Fold transport cannot cycle colours.
  B   the baryon winding of QLF_BaryonWinding (signed 3-axis linking over consecutive windows) is invariant under
      exactly the cyclic relabelings of the three axes and odd under the transpositions, over every word up to length 6.
      So the axis relabelings that preserve every baryon number form A3 = Z3: QLF's own colour Z3.
  C   on spinors, the cycle is the Clifford element U = (1 - i(sx + sy + sz))/2 (sec 23 D1), whose square carries omega.

Run:  python3 z3_colour_derivation.py
"""
from __future__ import annotations

import cmath
import itertools

from twist_core import pauli_fold

AXIS = {'>': 'x', '<': 'x', '^': 'y', 'v': 'y', '/': 'z', '\\': 'z', '+': None, '-': None}
LEVI = {('x', 'y', 'z'): 1, ('y', 'z', 'x'): 1, ('z', 'x', 'y'): 1,
        ('x', 'z', 'y'): -1, ('z', 'y', 'x'): -1, ('y', 'x', 'z'): -1}
POS = {'x': '>', 'y': '^', 'z': '/'}
NEG = {'x': '<', 'y': 'v', 'z': '\\'}


def rule(t: str) -> None:
    print("\n" + "=" * 78 + "\n" + t + "\n" + "-" * 78)


def baryon(word: str) -> int:
    ax = [AXIS[c] for c in word]
    return sum(LEVI.get((ax[i], ax[i + 1], ax[i + 2]), 0) for i in range(len(ax) - 2))


def relabel(word: str, perm: dict) -> str:
    out = []
    for c in word:
        a = AXIS[c]
        if a is None:
            out.append(c)
        else:
            out.append((POS if c in POS.values() else NEG)[perm[a]])
    return ''.join(out)


def mul(a, b):
    (a0, a1, a2, a3), (b0, b1, b2, b3) = a, b
    return (a0 * b0 + a1 * b2, a0 * b1 + a1 * b3, a2 * b0 + a3 * b2, a2 * b1 + a3 * b3)


def inv2(a):
    a0, a1, a2, a3 = a
    d = a0 * a3 - a1 * a2
    return (a3 / d, -a1 / d, -a2 / d, a0 / d)


def n1_n2():
    rule("N1, N2  THE FOLDS CARRY NO ORDER-3 PHASE AND NEVER CYCLE THE AXES")
    alphabet = list(AXIS)
    folds = {}
    for L in range(1, 5):
        for w in itertools.product(alphabet, repeat=L):
            f = pauli_fold(''.join(w))
            folds[tuple(complex(round(c.real, 9), round(c.imag, 9)) for c in f)] = f
    eig = set()
    for f in folds.values():
        a0, a1, a2, a3 = f
        tr, det = a0 + a3, a0 * a3 - a1 * a2
        disc = cmath.sqrt(tr * tr - 4 * det)
        for e in ((tr + disc) / 2, (tr - disc) / 2):
            eig.add(complex(round(e.real, 9), round(e.imag, 9)))
    print(f"  {len(folds)} distinct folds; all eigenvalues: {sorted(eig, key=lambda z: (z.real, z.imag))}")
    om = cmath.exp(2j * cmath.pi / 3)
    print(f"  omega among them: {any(abs(e - om) < 1e-9 or abs(e - om.conjugate()) < 1e-9 for e in eig)}"
          "   -> no fold has an order-3 phase (N1)")
    sig = {'x': (0, 1, 1, 0), 'y': (0, -1j, 1j, 0), 'z': (1, 0, 0, -1)}
    perms = set()
    for f in folds.values():
        image = []
        for a, s in sig.items():
            c = mul(mul(f, s), inv2(f))
            match = [b for b, t in sig.items() if all(abs(c[k] - t[k]) < 1e-9 or abs(c[k] + t[k]) < 1e-9 for k in range(4))
                     and any(abs(t[k]) > 0 for k in range(4))]
            image.append(match[0] if match else '?')
        perms.add(tuple(image))
    print(f"  axis images under conjugation by every fold: {sorted(perms)}   -> always (x, y, z) up to sign (N2)")


def b_test():
    rule("B  THE BARYON WINDING KNOWS A3 = Z3")
    words = [''.join(w) for L in range(3, 7) for w in itertools.product(list(POS.values()) + list(NEG.values()), repeat=L)]
    results = []
    for p in itertools.permutations('xyz'):
        perm = dict(zip('xyz', p))
        inv = all(baryon(relabel(w, perm)) == baryon(w) for w in words)
        odd = all(baryon(relabel(w, perm)) == -baryon(w) for w in words)
        kind = "preserves every baryon number" if inv else ("reverses every baryon number" if odd else "neither")
        results.append((p, inv))
        print(f"  x,y,z -> {','.join(p)}:  {kind}")
    keep = [p for p, ok in results if ok]
    print(f"\n  checked over {len(words)} words (lengths 3-6, the six spatial twists).")
    print(f"  relabelings preserving every baryon number: {[''.join(p) for p in keep]}  = A3, cyclic of order 3")


def c_test():
    rule("C  ITS SPINOR REALISATION IS CLIFFORD")
    print("  The cycle x -> y -> z on spinors is U = (1 - i(sx + sy + sz))/2 (sec 23 D1): U^3 = -I, U^2 carries omega.\n"
          "  By N1 and N2 it is not a fold and is not generated by fold transport.")


if __name__ == "__main__":
    n1_n2()
    b_test()
    c_test()
    print("""
Reading. QLF already contains the colour Z3, but as a symmetry, not a phase: the axis relabelings that leave every
baryon winding unchanged are exactly the three cyclic ones (B). On spinors that cycle is the Clifford element U, whose
square carries omega (C). It cannot come from the twist folds themselves -- their phases have order dividing 4 (N1)
and their transport never relabels axes (N2). So the sec 23 definition is now located precisely: colour's Z3 is the
baryon-preserving cyclic symmetry of the three axes, realised one level above the folds. What remains underived is
the flux: that a colour line carried around a mixed plaquette is cycled once (picks up U^2, i.e. omega).""")
